--- Makefile.old	2018-06-12 15:42:55.000000000 -0600
+++ Makefile	2018-06-12 15:43:09.000000000 -0600
@@ -12,7 +12,7 @@
 LE_CFLAGS = -DBF_LE
 
 JP_CFLAGS = $(CFLAGS_COMMON) \
-	    -I./jpeg-8a
+	    -I./jpeg-9a
 BF_CFLAGS = $(CFLAGS_COMMON)
 
 LIBS = -ljpeg
